version: '3'

services:
  postgresql_server:
    container_name: poc_postgresql_server
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=poc_db_user
      - POSTGRES_PASSWORD=poc_db_pass
      - POSTGRES_DB=poc_db_name
    volumes:
      - poc_volume_postgresql:/var/lib/postgresql/data
    networks:
      - poc_network

  postgresql_adminer:
    container_name: poc_postgresql_adminer
    image: adminer
    restart: always
    ports:
      - 7071:8080
    networks:
      - poc_network
    depends_on:
      - postgresql_server

  rabbitmq_server:
    container_name: poc_rabbitmq_server
    image: rabbitmq:3.7.7
    restart: always
    volumes:
      - poc_volume_rabbitmq:/var/lib/rabbitmq
    networks:
      - poc_network

  rabbitmq_management:
    container_name: poc_rabbitmq_management
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=poc_rmq_user
      - RABBITMQ_DEFAULT_PASS=poc_rmq_pass
    ports:
      - 7072:15672
    networks:
      - poc_network
    depends_on:
      - rabbitmq_server

  redis_server:
    container_name: poc_redis_server
    image: redis:4.0.11
    entrypoint: redis-server --appendonly yes
    restart: always
    volumes:
      - poc_volume_redis:/data
    networks:
      - poc_network

  redis_commander:
    container_name: poc_redis_commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis_server:6379
    ports:
      - 7073:8081
    networks:
      - poc_network
    depends_on:
      - redis_server

volumes:
  poc_volume_postgresql:
  poc_volume_rabbitmq:
  poc_volume_redis:

networks:
  poc_network:
    driver: bridge