version: '3'

services:
  postgresql_server:
    container_name: poc_postgresql_server
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=poc_db_user
      - POSTGRES_PASSWORD=poc_db_pass
      - POSTGRES_DB=poc_db_name
    volumes:
      - poc_volume_postgresql:/var/lib/postgresql/data
    networks:
      - poc_network

  postgresql_adminer:
    container_name: poc_postgresql_adminer
    image: adminer
    restart: always
    ports:
      - 9091:8080
    networks:
      - poc_network
    depends_on:
      - postgresql_server

  rabbitmq:
    container_name: poc_rabbitmq
    image: rabbitmq:3.7.7-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=poc_rmq_user
      - RABBITMQ_DEFAULT_PASS=poc_rmq_pass
    ports:
      - 9092:15672
    networks:
      - poc_network

  redis_server:
    container_name: poc_redis_server
    image: redis:4.0.11
    entrypoint: redis-server --appendonly yes
    restart: always
    volumes:
      - poc_volume_redis:/data
    networks:
      - poc_network

  redis_commander:
    container_name: poc_redis_commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis_server:6379
    ports:
      - 9093:8081
    networks:
      - poc_network
    depends_on:
      - redis_server

  sandbox:
    container_name: poc_sandbox
    image: node:8.11.4-alpine
    restart: always
    command: /bin/sh -c "npm install && tail -f /dev/null"
    working_dir: /sandbox
    volumes:
      - ./sandbox:/sandbox
    environment:
      - NODE_ENV=${NODE_ENV}
      - MESSAGE_QUEUE=amqp://poc_rmq_user:poc_rmq_pass@rabbitmq
    networks:
      - poc_network
    depends_on:
      - postgresql_server
      - rabbitmq
      - redis_server

  panel:
    container_name: poc_panel
    image: node:8.11.4-alpine
    restart: always
    command: /bin/sh -c "npm install && npm start"
    working_dir: /frontend/panel
    volumes:
      - ./frontend/panel:/frontend/panel
    environment:
      - PORT=9090
      - NODE_ENV=${NODE_ENV}
    ports:
      - 9090:9090
    networks:
      - poc_network

volumes:
  poc_volume_postgresql:
  poc_volume_rabbitmq:
  poc_volume_redis:

networks:
  poc_network:
    driver: bridge